### ISSUE TITLE
Error in training the model

### ISSUE THREAD

**Issue by anas-zafar** [3dlg-hcvc/OPDMulti#3]
Thanks for the amazing work @Sun-XH. I am trying to reproduce the results mentioned in the paper. I am having this issue while training on OPD Multi dataset, using pretrained weights of OPD Real to train OPDFormer-O. Could you please guide me if I am missing out something

```
Config '/home/research/OPDMulti/data/OPDMulti/obj_info.json' has no VERSION. Assuming it to be compatible with latest v2.
Traceback (most recent call last):
  File "train.py", line 179, in <module>
    args=(args,),
  File "/home/ubuntu/anaconda3/envs/opdmulti/lib/python3.7/site-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train.py", line 160, in main
    cfg = setup_cfg(args)
  File "train.py", line 51, in setup_cfg
    cfg.merge_from_file(args.config_file)
  File "/home/ubuntu/anaconda3/envs/opdmulti/lib/python3.7/site-packages/detectron2/config/config.py", line 54, in merge_from_file
    self.merge_from_other_cfg(loaded_cfg)
  File "/home/ubuntu/anaconda3/envs/opdmulti/lib/python3.7/site-packages/fvcore/common/config.py", line 132, in merge_from_other_cfg
    return super().merge_from_other_cfg(cfg_other)
  File "/home/ubuntu/anaconda3/envs/opdmulti/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/ubuntu/anaconda3/envs/opdmulti/lib/python3.7/site-packages/yacs/config.py", line 491, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: scene_00000_00_0_1'
```

**Comment by Sun-XH** [comment]
Hi there,
Thanks for your interest. From the error, I believe that you're using the wrong config file. The `obj_info.json` is the model_attr_file, which should be filled to the `model_attr_path`. The README file has a detailed instruction on what config file you should use. For example, if you want to train the -O version, the config file should be `OPDMulit/opdformer/configs/opd_o_real.yaml `
Hope this can solve your issue.

**Comment by anas-zafar** [comment]
Thanks for point that out. I fixed the above issues, Below is another adherent issue I am facing. I tried setting up the env again as well as reinstalling pytorch.

Traceback (most recent call last):
  File "train.py", line 30, in <module>
    from mask2former import (
  File "/home/research/OPDMulti/opdformer/mask2former/__init__.py", line 3, in <module>
    from . import modeling
  File "/home/research/OPDMulti/opdformer/mask2former/modeling/__init__.py", line 4, in <module>
    from .pixel_decoder.msdeformattn import MSDeformAttnPixelDecoder
  File "/home/research/OPDMulti/opdformer/mask2former/modeling/pixel_decoder/msdeformattn.py", line 19, in <module>
    from .ops.modules import MSDeformAttn
  File "/home/research/OPDMulti/opdformer/mask2former/modeling/pixel_decoder/ops/modules/__init__.py", line 12, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "/home/research/OPDMulti/opdformer/mask2former/modeling/pixel_decoder/ops/modules/ms_deform_attn.py", line 24, in <module>
    from ..functions import MSDeformAttnFunction
  File "/home/research/OPDMulti/opdformer/mask2former/modeling/pixel_decoder/ops/functions/__init__.py", line 12, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "/home/research/OPDMulti/opdformer/mask2former/modeling/pixel_decoder/ops/functions/ms_deform_attn_func.py", line 22, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: /home/ubuntu/anaconda3/envs/opdmulti/lib/python3.7/site-packages/MultiScaleDeformableAttention-1.0-py3.7-linux-x86_64.egg/MultiScaleDeformableAttention.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe28TypeMeta21_typeMetaDataInstanceIdEEPKNS_6detail12TypeMetaDataEv
